# Generated by Django 4.0 on 2022-05-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_emp', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_emp', models.CharField(max_length=25)),
                ('apellido_emp', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_ciudad', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleHorario',
            fields=[
                ('id_hor_det', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_desde', models.DateField()),
                ('hora_hasta', models.DateField()),
            ],
            options={
                'db_table': 'detalle_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('lugar', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Duenno',
            fields=[
                ('rut_duenno', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('pnombre', models.CharField(max_length=30)),
                ('snombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apaterno', models.CharField(max_length=30)),
                ('amaterno', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'duenno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_marca', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_modelo', models.CharField(max_length=50)),
                ('annio', models.IntegerField()),
            ],
            options={
                'db_table': 'modelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.IntegerField(primary_key=True, serialize=False)),
                ('letra_puesto', models.CharField(max_length=2)),
                ('num_puesto', models.IntegerField()),
            ],
            options={
                'db_table': 'puesto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dia_reserva', models.IntegerField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SucursalEst',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_sucursal', models.CharField(max_length=30)),
                ('fono_suc', models.IntegerField()),
            ],
            options={
                'db_table': 'sucursal_est',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut_user', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('pnombre', models.CharField(max_length=30)),
                ('snombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apaterno', models.CharField(max_length=30)),
                ('amaterno', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=45)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=25)),
                ('num_ruedas', models.BooleanField()),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
    ]
