# Generated by Django 4.0 on 2022-06-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0003_alter_sucursalest_direccion_lugar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursalest',
            old_name='id',
            new_name='id_suc',
        ),
    ]
